name: create-listing
on: 
  workflow_dispatch:
    inputs:
      item_number:
        required: true
      category:
        required: true
        type: choice
        options:
          - 'seedlings'
          - 'clones'
          - 'mutated'
          - 'other'
      description:
        required: true
        default: 'Description coming soon.'
      price:
        required: true
        default: 0
      is_sold:
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Write item number to file
        run: |
          echo "${{ github.event.inputs.item_number }}" > test.txt

      