name: create-listing
on: 
  workflow_dispatch:
    inputs:
      item_number:
        required: true
        type: string
        description: |
          item_number
          (Do not use these characters: <, >, &, \", ', \\)
      category:
        required: true
        type: choice
        options:
          - 'seedlings'
          - 'clones'
          - 'mutated'
          - 'other'
      description:
        required: true
        type: string
        description: |
          description
          (Do not use these characters: <, >, &, \", ', \\)
        default: 'Description coming soon.'
      price:
        required: true
        type: number
        description: |
          price
          (Numbers only)
        default: 0
      is_sold:
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'
jobs:
  update_xml:
    runs-on: ubuntu-latest
    steps:
      - name: validate inputs
        run: |
          item_number="${{ inputs.item_number }}"
          description="${{ inputs.description }}"
          price="${{ inputs.price }}"

          if [[ "$item_number" =~ [\<\>\&\"\'\\] ]]; then
            echo "Error: 'item_number' must not include special characters."
            exit 1
          fi

          if [[ "$description" =~ [\<\>\&\"\'\\] ]]; then
            echo "Error: 'description' must not include special characters."
            exit 1
          fi

          if ! [[ "$price" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            echo "Error: 'price' must be a valid number."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Install XMLstarlet
        run: |
          sudo apt-get update
          sudo apt-get install xmlstarlet -y

      - name: Update XML listing
        run: |
          xmlstarlet ed -s "/listings" -t elem -n "listing" -v " " static/xml/listings.xml | \
          xmlstarlet ed -s "/listings/listing[last()]" -t elem -n "itemNumber" -v "${{ github.event.inputs.item_number }}" | \
          xmlstarlet ed -s "/listings/listing[last()]" -t elem -n "category" -v "${{ github.event.inputs.category }}" | \
          xmlstarlet ed -s "/listings/listing[last()]" -t elem -n "description" -v "${{ github.event.inputs.description }}" | \
          xmlstarlet ed -s "/listings/listing[last()]" -t elem -n "price" -v "${{ github.event.inputs.price }}" | \
          xmlstarlet ed -s "/listings/listing[last()]" -t elem -n "isSold" -v "${{ github.event.inputs.is_sold }}" > static/xml/temp.xml
          mv static/xml/temp.xml static/xml/listings.xml
          
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          # Set the remote URL with the PAT for authentication
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/ambrose-s/cactus-website.git
          git add static/xml/listings.xml
          if [[ $(git diff --cached --name-only) ]]; then
            git commit -m "Add new listing: ${{ github.event.inputs.item_number }}"
            git push
          else
            echo "No changes to commit."
          fi